// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDw5P8zZ4Z0h-kGxD5WcifWafDTJcJ0ZfY',
    appId: '1:502449646798:web:d9e49dcea4e678b4e1749f',
    messagingSenderId: '502449646798',
    projectId: 'plv-algerie-test-cd400',
    authDomain: 'plv-algerie-test-cd400.firebaseapp.com',
    storageBucket: 'plv-algerie-test-cd400.appspot.com',
    measurementId: 'G-WVQ2ZW84ME',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWIcVofOTMBS2veB_6ENJONisfRVWb8mU',
    appId: '1:502449646798:android:f532503254a96e2de1749f',
    messagingSenderId: '502449646798',
    projectId: 'plv-algerie-test-cd400',
    storageBucket: 'plv-algerie-test-cd400.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQ45HuxqX5Ys7Sj0M10ntXLhtRUnprVY8',
    appId: '1:502449646798:ios:91aa8cd3c1abaef5e1749f',
    messagingSenderId: '502449646798',
    projectId: 'plv-algerie-test-cd400',
    storageBucket: 'plv-algerie-test-cd400.appspot.com',
    iosBundleId: 'com.example.plv',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQ45HuxqX5Ys7Sj0M10ntXLhtRUnprVY8',
    appId: '1:502449646798:ios:91aa8cd3c1abaef5e1749f',
    messagingSenderId: '502449646798',
    projectId: 'plv-algerie-test-cd400',
    storageBucket: 'plv-algerie-test-cd400.appspot.com',
    iosBundleId: 'com.example.plv',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDw5P8zZ4Z0h-kGxD5WcifWafDTJcJ0ZfY',
    appId: '1:502449646798:web:af5dfcec51d2ab5ae1749f',
    messagingSenderId: '502449646798',
    projectId: 'plv-algerie-test-cd400',
    authDomain: 'plv-algerie-test-cd400.firebaseapp.com',
    storageBucket: 'plv-algerie-test-cd400.appspot.com',
    measurementId: 'G-4HFDP3W0J9',
  );
}
